export const SERVER_URL=" https://asishsabu.space"
export const BASE_URL=SERVER_URL+"/api/"
export const USER_API=BASE_URL+"user";
export const OWNER_API=BASE_URL+"owners";
export const ADMIN_API=BASE_URL+"admin";
export const NUMBER_REGEX=/[a-z]/gi
export const nameRegex = /^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$/;
export const emailRegex = /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$/;
export const descriptionRegex = /^[A-Z][A-Za-z\s,.-]*$/;
export const phoneRegex = /^\d{10}$/;
export const timeRegex = /^(0[1-9]|1[0-2]):[0-5][0-9] (AM|PM|am|pm)$/;
export const CLOUDINARY_UPLOAD_API ="https://api.cloudinary.com/v1_1/di6vby1gu/image/upload";
export const cloudinaryUploadPreset = "preset";